name: Test

on:
  push:
    branches:
    - '**'

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        submodules: true
    - name: Build iPXE binary
      run: |
        sudo apt-get install liblzma-dev
        cd ipxe/src
        cp ../../general.h config/local/
        make bin/ipxe.lkrn
        sha256sum bin/ipxe.lkrn > bin/ipxe.lkrn.sha256
